version: "3.8"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./instance:/opt/app/instance

  nginx:
    image: nginx:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend/assets:/usr/share/nginx/html/assets:ro
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
